### ISSUE TITLE
firstboot_pkgs_list will not work if behind a proxy

### ISSUE THREAD

**Issue by tardyp** [brd/packer-freebsd#17]
Trying to make this work behind a corporate proxy, I finally figured out that the box can't work because sudo will never be installed.

I can boot by CTR-C in the console, but will never be able to sudo in this box.

Note that I could work around that by using the root password "vagrant"

**Comment by tardyp** [comment]
because of issue with ansible, I cannot automate installation of sudo :-(

https://github.com/ansible/ansible/issues/12537

**Comment by brd** [comment]
You could set the proxy in the environment so that it will be used.

**Comment by tardyp** [comment]
Yes, I can set the proxy in the environment, and this works.
But I cannot fully automate the vagrant provisioning with this. I need to make some manual setup after vagrant up.

You can see how I am using this vagrant image: https://github.com/buildbot/buildbot-infra/pull/148

and the note about proxies:
+Development with proxies
 +------------------------
 +Because of https://github.com/brd/packer-freebsd/issues/17 the boostrap will not work.
 +upon VM creation by vagrant, vagrant will indefinitly try to connect via ssh.
 +- You need to run virtualbox manually, and go to the freebsd console.
 +- Hit CTRL-C will stop the firstboot script and give you login prompt
 +- use root:vagrant
 +- setenv http_proxy http://xxx
 +- pkg install -y sudo
 +- then you can run 'vagrant provision' again
 +

**Comment by brd** [comment]
I am suggesting you modify the packer recipe to add the proxy to the environment as part of the install.  That way when it boots for the first time, the proxy is already set.

**Comment by tardyp** [comment]
well having to build my own version of the VM defeast the purpose of using your cool prebuilt ones :)

wouldn't it be possible to do the first boot as part of the packer recipe, so that the VM is already initialized?

**Comment by brd** [comment]
I am confused.  If you are using this packer recipe you are building your own VM.

**Comment by tardyp** [comment]
I am using https://atlas.hashicorp.com/freebsd/boxes/FreeBSD-10.3-STABLE which I understand is generated using this reciepe

**Comment by brd** [comment]
No.  That is generated by the FreeBSD make release process, which does not use packer at all.
