### ISSUE TITLE
password retyping fails

### ISSUE THREAD

**Issue by robinlehrmann** [brd/packer-freebsd#20]
Hi,

if I run the automatic scripts with version 11.0, it fails on password retype for root and vagrant user.
It didn't match.

Do you have any ideas to resolve the problem ?

(My suggestion would be to use only ssh-key authorization without typing a password.)

Cheers,
Robin

**Comment by sean-** [comment]
That sounds like a timing problem and like something is being clipped during entry.  Can you verify that adding some `<wait>` and `<wait10>` calls doesn't fix things?

**Comment by robinlehrmann** [comment]
I've already tried out with <wait><wait10> but IT didn't solve The problem :(.

**Comment by sean-** [comment]
Interesting... last time I tried it worked.  This is boiling up my priority stack again now that there's an EBS Surrogate builder that can be used to build ZFS root volumes in AWS (https://github.com/mitchellh/packer/pull/4351).

**Comment by sean-** [comment]
I'm closing this issue because I believe it's been resolved in `master`. If not, feel free to reopen.
