### ISSUE TITLE
Old releases like 7.0

### ISSUE THREAD

**Issue by korjavin** [brd/packer-freebsd#22]
I have some legacy, 7.0 freebsd box.

Is it possible to get or build vagrant image for it?

**Comment by sean-** [comment]
Do you have an iso?  You can certainly build a packer file for a FreeBSD 7.0 file, but the provided packer templates won't work for FreeBSD 7.0.

If you have a specific question, drop an issue, but to answer your specific question: yes, it's possible to build a vagrant image for FreeBSD 7.0.  Let us know!  If you get a working 7.0 packer template we'd add it to the repo.
