### ISSUE TITLE
FreeBSD current template is invalid

### ISSUE THREAD

**Issue by LogicalChaos** [brd/packer-freebsd#4]
The file referenced doesn't exist anymore: http://ftp.freebsd.org/pub/FreeBSD/snapshots/ISO-IMAGES/11.0/FreeBSD-11.0-CURRENT-amd64-20150111-r276981-disc1.iso

Seems like template-current.json needs to be dynamically generated by examining the ftp site and parsing out the latest iso and checksum files.  Maybe get the FreeBSD guys to post a link something like FreeBSD-11.0-CURRENT-amd64-LATEST.iso (and it's checksum).

**Comment by brd** [comment]
:D
